[package]
name = "mirith"
version = "0.1.0"
authors = ["mrezahassani@protonmail.com"]
edition = "2021"

[features]
default = ["reference"]
reference = []
optimized = []
avx2 = []
neon = []
# cortex-m4 = []
hypercube = []

ia = []
ib = []
iiia = []
iiib = []
va = []
vb = []

fast = []
short = []
shorter = []
shortest = []

[dependencies]
config = "0.14.0"
serde = { version = "1.0.202", features = ["derive"] }

[profile.release]
debug = true
lto = true
codegen-units = 1
